version: "3.7"
services:
#  api_service:
#    build: .
#    restart: always
#    ports:
#      - "8080:8080"
#    depends_on:
#      - postgresql_db
#    links:
#      - postgresql_db:postgresql_db
  postgresql_db:
    image: "postgres:15-alpine3.17"
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: publisher
      POSTGRES_USER: postres
      POSTGRES_PASSWORD: password123