version: "3.7"
services:
  api_service:
    container_name: nine-article-publisher-service
    image: eallanjoseph/nine-article-publisher-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9191:9191"
    depends_on:
      publisher-db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://publisher-db:3306/publisher?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
  publisher-db:
    image: mysql:5.7.17
    container_name: publisher-db
    restart: always
    healthcheck:
        test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
        timeout: 20s
        retries: 10
    ports:
      - 3306:3306
    volumes:
      - mysqldata:/var/lib/lunch
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=publisher
volumes:
  mysqldata:
    external: false